### PR TITLE
chore(contracts): add function to deploy contracts deterministically

### LINKED ISSUE #766: Deploy Semaphore contracts deterministically
**Description**

In order for Semaphore contracts to have the same address on all supported networks, it is necessary to deploy them deterministically, using the CREATE2 opcode.

A proxy Yul contract like [Zoltu's implementation](https://github.com/Arachnid/deterministic-deployment-proxy), or the updated [Arachnid's version](https://github.com/Arachnid/deterministic-deployment-proxy), can be used to deploy the Semaphore contracts by passing their bytecode + salt.

### PR DESCRIPTION
**Pull request by cedoor**
## Related Issue(s)

Closes #766

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vplasencia** [comment]
Hey @cedoor thank you for this PR. Could you check the tests? It looks like there are some tests failing.

**Comment by cedoor** [comment]
@vplasencia Yes, I should have fixed it. Let's see

**Review by vplasencia — APPROVED** [review]
Great work! Thank you very much.

**Review by sripwoud — COMMENTED** [review]
post merge utACK

**Pull request merged**
