### PR TITLE
Update `utils` package and identity private key types.

### LINKED ISSUE #641: Provide a list of networks supported by Semaphore and the deployed addresses per network in `@semaphore-protocol/utils`

### LINKED ISSUE #642: Provide a utility function to convert uint256 (bigints) to strings with `decodeBytes32String` in `@semaphore-protocol/utils`

### LINKED ISSUE #700: New private key types
**Description**:

The type of the identities' private key are currently many: bigint, number, string, Buffer etc. This may generate confusion and it makes the process of storing private keys harder, as devs will need to convert values more often.

One type only could be supported instead: `string`, which may be either text (e.g. a password/secret) or a hexadecimal string (without `0x`/`0X` as a prefix). This would also make all the Identity attributes the same type.

### PR DESCRIPTION
**Pull request by cedoor**
## Description

The utils package will no longer provide `errors` and `types` utilities as those functions have been moved to [ZK-Kit](https://github.com/privacy-scaling-explorations/zk-kit). The utils package now provides a list of supported networks and a function to decode messages instead.

The type of the identities' private key will always be a string type, either text or hexadecimal strings. This will allow devs to store private keys more easily and avoid confusion with types.

This PR still needs a fix in the `@zk-kit/eddsa-poseidon` library -> https://github.com/privacy-scaling-explorations/zk-kit/issues/187. Need to fix that before merging.

## Related Issue(s)

Closes #700
Closes #642
Closes #641

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vplasencia — APPROVED** [review]
It looks great! Thanks. It's nice to see `supported-networks`, `decode-message` and the update in the `Identity` package. 

There is an issue when running `yarn test`

**Comment by cedoor** [comment]
Thanks!

> There is an issue when running `yarn test`

Yes, waiting for a ZK-Kit fix.

**Comment by andyguzmaneth** [comment]
@gitpoap-bot @cedoor

**Comment by andyguzmaneth** [comment]
@gitpoap-bot @vplasencia

**Comment by andyguzmaneth** [comment]
@gitpoap-bot @0xjei

**Pull request merged**
