### PR TITLE
chore: set up `turbo`

### LINKED ISSUE #745: Integrate Turbo
- [ ] semaphore repo
- [ ] extensions repo

### PR DESCRIPTION
**Pull request by sripwoud**
WIP

## Description
Set up [`turbo`](https://turbo.build/) to run tasks and cache their results for operations related to:
- buildings apps and packages
- linting
- formatting
- testing

||Before|After|
|---|---|---|
|tasks dependencies|none, needs to manually run necessary build tasks before executing linting or testing tasks|defined, turbo will automatically run and wait for build tasks to complete before linting or testing|
|speed (ex: building then testing libraries)|pic-selected-240502-1553-29|pic-selected-240502-1554-48|

## Related Issue(s)
Closes #745

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sripwoud** [comment]
I am not sure whether the failing test is related to my PR?
https://github.com/semaphore-protocol/semaphore/actions/runs/8925027515/job/24512736232#step:7:426
Looks like a matchtick install/config error no?

**Comment by cedoor** [comment]
> I am not sure whether the failing test is related to my PR? https://github.com/semaphore-protocol/semaphore/actions/runs/8925027515/job/24512736232#step:7:426 Looks like a matchtick install/config error no?

It looks like it's trying to run tests on the Semaphore subgraph without running `yarn codegen` first, which should generate the `subgraph.yaml` file.

Maybe `yarn style` is not enough, it also needs to `yarn build:subgraph` somewhere.

**Comment by sripwoud** [comment]
Fixed in last commit.
We should decide what to merge first though: #765 or #757
I think I'd prefer merging #765 first and then reworking #757

**Comment by cedoor** [comment]
> Fixed in last commit. We should decide what to merge first though: #765 or #757 I think I'd prefer merging #765 first and then reworking #757

Merged!

**Review by vplasencia — APPROVED** [review]
LGTM! Thanks @sripwoud

**Comment by sripwoud** [comment]
re error when running subgraph test script:
I don't think it is up to semaphore to document this or prevent it from happenning. Just want to share in case it comes up again for someone.
I had 2 errors related to the installation of https://github.com/graphprotocol/graph-tooling/tree/main/packages/cli  on linux environment (arch) due to missing lower level libraries:
```
semaphore/node_modules/binary-install-raw/bin/0.5.0/binary-linux-20: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```
solved by installing [`postgresql-libs`](https://archlinux.org/packages/extra/x86_64/postgresql-libs/)

and then
```
semaphore/node_modules/binary-install-raw/bin/0.5.0/binary-linux-20: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
solved by installing [`openssl-1.1`](https://archlinux.org/packages/core/x86_64/openssl-1.1/)

**Comment by cedoor** [comment]
@sripwoud  should we close this issue?

**Comment by sripwoud** [comment]
Yes let's close this,
Alternatively I suggest https://github.com/semaphore-protocol/semaphore/pull/810 to speed up the execution of local scripts

**Pull request closed without merging**
