### PR TITLE
chore: update zk-kit dependencies

### LINKED ISSUE #776: Update zk-kit dependencies
**Tasks**:

- [x] `@zk-kit/binary-merkle-root.circom`
- [x] `@zk-kit/imt`
- [x] `@zk-kit/imt.sol`
- [x] `@zk-kit/eddsa-poseidon`
- [x] `@zk-kit/utils`
- [x] `@zk-kit/baby-jubjub`

### PR DESCRIPTION
**Pull request by vplasencia**
## Description

This PR updates some zk-kit dependencies.

## Related Issue(s)

Closes https://github.com/semaphore-protocol/semaphore/issues/776

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cedoor** [comment]
I'd say we can keep this PR open until we release stable versions for those packages (probably today), so that you can update them again one last time. What do you think?

**Comment by vplasencia** [comment]
@cedoor Perfect, makes sense.

**Comment by vplasencia** [comment]
@cedoor please, let me know when the stable releases are ready.

**Comment by cedoor** [comment]
@vplasencia Yes! I need more time because the imt libraries will be split into two different packages.

`@zk-kit/baby-jubjub` and `@zk-kit/eddsa-poseidon` are ready!

**Review by cedoor — APPROVED** [review]

**Pull request merged**
