### PR TITLE
refactor(contracts): specify gas cost in SemaphoreVerifier precompile calls

### LINKED ISSUE #871: Remove sub() from gas() in SemaphoreVerifier.sol
There are [lines in SemaphoreVerifier.sol](https://github.com/semaphore-protocol/semaphore/blob/4c2769099f508366695a6ccc7223023daff087c9/packages/contracts/contracts/base/SemaphoreVerifier.sol#L575) that make `gas()` calls. GAS opcode is restricted in validateUserOp ([along with some other OPCODES](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4337.md#forbidden-opcodes)). GAS is only allowed if immediately followed by CALL (and similar) opcodes. Semaphore does `staticcall(sub(gas(), ...)` and there is a `SUB` in between.

So we need some other way to take the gas cost in consideration.

- related: #345
- refer also to this blog post (**other challenges** section):
https://saleel.xyz/blog/zk-account-abstraction/

### PR DESCRIPTION
**Pull request by jimmychu0807**
## Description

Close #871 

## Other Info 

Original gas usage:

```
·-----------------------------------------------|---------------------------|-------------|-----------------------------·
|             Solc version: 0.8.23              ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
················································|···························|·············|······························
|  Methods                                                                                                              │
··············|·································|·············|·············|·············|···············|··············
|  Contract   ·  Method                         ·  Min        ·  Max        ·  Avg        ·  # calls      ·  usd (avg)  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  acceptGroupAdmin               ·          -  ·          -  ·      29066  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  addMember                      ·     117970  ·     157140  ·     133880  ·           15  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  addMembers                     ·     222218  ·     302814  ·     288637  ·            6  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·      54745  ·      91757  ·      82504  ·            4  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·          -  ·          -  ·      91038  ·            3  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·      74496  ·      91596  ·      90281  ·           26  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  removeMember                   ·          -  ·          -  ·     128981  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateGroupAdmin               ·          -  ·          -  ·      48343  ·            4  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateGroupMerkleTreeDuration  ·          -  ·          -  ·      30748  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateMember                   ·          -  ·          -  ·     212377  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  validateProof                  ·          -  ·          -  ·     290144  ·            5  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Deployments                                  ·                                         ·  % of limit   ·             │
················································|·············|·············|·············|···············|··············
|  PoseidonT3                                   ·          -  ·          -  ·    3693362  ·       12.3 %  ·          -  │
················································|·············|·············|·············|···············|··············
|  Semaphore                                    ·          -  ·          -  ·    1820135  ·        6.1 %  ·          -  │
················································|·············|·············|·············|···············|··············
|  SemaphoreVerifier                            ·          -  ·          -  ·    3722864  ·       12.4 %  ·          -  │
·-----------------------------------------------|-------------|-------------|-------------|---------------|-------------·
```

With this PR (last updated 2024-10-31):

```
·-----------------------------------------------|---------------------------|-------------|-----------------------------·
|             Solc version: 0.8.23              ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
················································|···························|·············|······························
|  Methods                                                                                                              │
··············|·································|·············|·············|·············|···············|··············
|  Contract   ·  Method                         ·  Min        ·  Max        ·  Avg        ·  # calls      ·  usd (avg)  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  acceptGroupAdmin               ·          -  ·          -  ·      29066  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  addMember                      ·     117970  ·     157140  ·     133880  ·           15  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  addMembers                     ·     222218  ·     302814  ·     288637  ·            6  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·      54745  ·      91757  ·      82504  ·            4  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·          -  ·          -  ·      91038  ·            3  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  createGroup                    ·      74496  ·      91596  ·      90281  ·           26  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  removeMember                   ·          -  ·          -  ·     128981  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateGroupAdmin               ·          -  ·          -  ·      48343  ·            4  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateGroupMerkleTreeDuration  ·          -  ·          -  ·      30748  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  updateMember                   ·          -  ·          -  ·     212377  ·            2  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Semaphore  ·  validateProof                  ·          -  ·          -  ·     290063  ·            5  ·          -  │
··············|·································|·············|·············|·············|···············|··············
|  Deployments                                  ·                                         ·  % of limit   ·             │
················································|·············|·············|·············|···············|··············
|  PoseidonT3                                   ·          -  ·          -  ·    3693362  ·       12.3 %  ·          -  │
················································|·············|·············|·············|···············|··············
|  Semaphore                                    ·          -  ·          -  ·    1820135  ·        6.1 %  ·          -  │
················································|·············|·············|·············|···············|··············
|  SemaphoreVerifier                            ·          -  ·          -  ·    3721580  ·       12.4 %  ·          -  │
·-----------------------------------------------|-------------|-------------|-------------|---------------|-------------·
```

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jimmychu0807** [comment]
@chancehudson @cedoor 
After some experimenting, I decide to code on the defensive side and specify the gas cost in the precompile calls (@chancehudson has suggested that as well). 

Based on EVM code reference (https://www.evm.codes/precompiled), 0x07 `ecMul` is fixed to use **6000** gas, and 0x06 `ecAdd` is fixed to use **150** gas when inputs are valid. If inputs are invalid, gas are consumed and the following check `iszero(success)` will become true and return.

For the 0x08 `ecPairing` gas cost, it [used to be](https://eips.ethereum.org/EIPS/eip-197#gas-costs) `80000*k + 100000`, where k is the number of points or, equivalently, the length of the input divided by 192. But in the latest EVM it seems to become `34000*k + 45000`, this is also confirmed in the above EVM code reference after you specify the input byte size.

Screenshot 2024-10-27 at 14 05 58

This change is very EVM implementation-specific, but as EVM iterates I believe the gas cost will likely only decrease and not increase, so specifying the max gas cost to use should be fine.

**Comment by jimmychu0807** [comment]
On a side note, I have this experimenting code here:
https://github.com/jimmychu0807/semaphore/blob/jc%2Fplayground/packages/contracts/contracts/base/SemaphoreVerifier.sol#L38-L117

Even if I pass in invalid input parameters to `ecAdd`, `ecMul`, and `ecPairing` calls, or pass in insufficient gas to these calls, they won't revert. They will just fail and have `success` returns 0, which is good. 

But I am not sure if this is hardhat node implementation specific or is part of the specification, so erring on the defensive side.

**Comment by cedoor** [comment]
@jimmychu0807 Thanks for this PR, it looks like the best solution to me.

> This change is very EVM implementation-specific, but as EVM iterates I believe the gas cost will likely only decrease and not increase, so specifying the max gas cost to use should be fine.

I'm not sure about this. I'd like to know what @chancehudson thinks about it.

Also a review from @0xDatapunk and @thogiti would be great!

**Comment by jimmychu0807** [comment]
Thanks 0xDatapunk for the review. @chancehudson @thogiti if you have time these few days could you take a look at this PR. The code change is just 3 lines, changing from `gas()` to a fixed gas cost. Please take a look at the discussion above on my reasoning and see if this makes sense to you. Thank you for your time!

**Comment by chancehudson** [comment]
I'd recommend sending ~20% extra gas with each call - I've seen other similar cases that did this. The sent gas will simply be refunded so it should not change the final price of the transaction.

Hardcoding gas numbers like this is _very_ brittle so safety measures should be taken.

**Comment by jimmychu0807** [comment]
This makes sense to me. Should add some extra gas as buffer.

**Comment by jimmychu0807** [comment]
Increased gas cost with safety buffer of 33.3%, just want to reserve a bit wider margin. Gas report generated by `yarn test:gas-report` is updated at [the PR desc](https://github.com/semaphore-protocol/semaphore/pull/883#issue-2608865942), still less than before the PR.

**Comment by thogiti** [comment]
Looks good. 

Please add more detailed documentation on these changes. 

Please make sure to update the fixed gas costs numbers for any future updates.

**Review by cedoor — APPROVED** [review]
Looks like it's ready to be merged!

Thanks @jimmychu0807 🙏🏽

**Comment by jimmychu0807** [comment]
thank you @chancehudson @thogiti @0xdatapunk for the input!

**Pull request merged**
